<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use App\Models\Tenant;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class RegisterTenantController extends Controller
{
    public function __invoke(Request $request)
    {
        Log::info('RegisterTenantController invoked');
        $data = $request->validate([
            'company' => ['required', 'string', 'max:255'],
            'slug' => ['nullable', 'alpha_dash', 'max:64', 'unique:tenants,slug'],
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'email', 'max:255'],
            'password' => ['required', 'string', 'min:8', 'regex:/\d/', 'regex:/[^A-Za-z0-9]/', 'confirmed'],
            'domain' => ['nullable', 'string', 'max:255', 'unique:tenants,domain'],
        ]);

        // 1. Create Tenant (Landlord DB)
        $baseSlug = $data['slug'] ?? Str::slug($data['company']);
        $slug = $this->uniqueTenantSlug($baseSlug);

        // Determine domain
        $suffix = config('app.tenant_domain_suffix', 'localhost');
        // Ensure suffix doesn't start with dot if we are appending it
        $suffix = ltrim($suffix, '.');

        $domain = $data['domain'] ?? ($slug . '.' . $suffix);

        Log::info('Creating tenant with slug: ' . $slug);

        try {
            $tenant = Tenant::create([
                'name' => $data['company'],
                'slug' => $slug,
                'domain' => $domain,
                // database is auto-generated by model event
            ]);
            Log::info('Tenant created: ' . $tenant->id . ', DB: ' . $tenant->database);
        } catch (\Throwable $e) {
            Log::error('Tenant Create Error: ' . $e->getMessage());
            throw $e;
        }

        // 2. Create Tenant Database
        try {
            $this->createTenantDatabase($tenant);
            Log::info('Tenant DB created');
        } catch (\Throwable $e) {
            $tenant->delete();
            Log::error('Create DB Error: ' . $e->getMessage());
            throw $e;
        }

        // 3. Switch to Tenant Context
        try {
            $tenant->makeCurrent();
            Log::info('Switched to tenant context');
        } catch (\Throwable $e) {
            Log::error('Tenant Context Switch Error: ' . $e->getMessage());
            throw $e;
        }

        // 4. Run Migrations (Tenant DB)
        try {
            \Illuminate\Support\Facades\Artisan::call('migrate', [
                '--database' => 'tenant',
                '--path' => 'database/migrations/tenant',
                '--force' => true,
            ]);
            Log::info('Migrations run');
        } catch (\Throwable $e) {
            Log::error('Migration Error: ' . $e->getMessage());
            throw $e;
        }

        // 5. Create Admin User (Tenant DB)
        try {
            $admin = User::create([
                'name' => $data['name'],
                'email' => $data['email'],
                'password' => $data['password'],
                'role' => 'owner',
            ]);
            Log::info('Admin user created: ' . $admin->id);
        } catch (\Throwable $e) {
            Log::error('User Create Error: ' . $e->getMessage());
            throw $e;
        }

        try {
            $token = $admin->createToken('pat')->plainTextToken;
        } catch (\Throwable $e) {
            Log::error('Token Create Error: ' . $e->getMessage());
            throw $e;
        }

        return response()->json([
            'tenant' => [
                'uid' => $tenant->uid,
                'name' => $tenant->name,
                'slug' => $tenant->slug,
                'domain' => $tenant->domain,
            ],
            'user' => [
                'uid' => $admin->uid,
                'name' => $admin->name,
                'email' => $admin->email,
                'role' => $admin->role,
            ],
            'token' => $token,
        ], 201);
    }

    private function createTenantDatabase(Tenant $tenant): void
    {
        $databaseName = $tenant->database;

        // Ensure we are on landlord connection to create DB
        // We use a separate connection or raw PDO if needed, but usually the default connection user has rights
        // We need to run this query on the 'landlord' connection (which should be the default or explicit)

        // Postgres: CREATE DATABASE "name"
        // We must ensure the name is safe. It is generated by ULID/Slug so it should be safe-ish, but let's be careful.

        // Note: You cannot run CREATE DATABASE inside a transaction block in Postgres.
        // So we must ensure this is not in a transaction.

        // DB::connection('landlord')->statement("CREATE DATABASE \"{$databaseName}\"");

        // Use a fresh PDO connection to avoid "CREATE DATABASE cannot run inside a transaction block"
        $config = config('database.connections.landlord');
        // Construct DSN manually or use a helper if available, but manual is safer here to ensure isolation
        $dsn = "pgsql:host={$config['host']};port={$config['port']};dbname={$config['database']}";

        try {
            $pdo = new \PDO($dsn, $config['username'], $config['password']);
            $pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
            $pdo->exec("CREATE DATABASE \"{$databaseName}\"");
        } catch (\PDOException $e) {
            // If database already exists, we might want to ignore or handle it
            // For now, let it throw so we know
            throw new \Exception("Failed to create database: " . $e->getMessage());
        }
    }

    private function uniqueTenantSlug(string $base): string
    {
        $slug = Str::lower($base);
        $slug = preg_replace('/[^a-z0-9\-]+/', '-', $slug);
        $slug = trim(preg_replace('/-+/', '-', $slug), '-');

        if ($slug === '') {
            $slug = 'tenant';
        }

        $try = $slug;
        $i = 1;
        while (Tenant::where('slug', $try)->exists()) {
            $try = $slug . '-' . $i++;
        }
        return $try;
    }
}
